-- Insert premade public templates with system user ID
INSERT INTO public.content_templates (user_id, name, prompt, platforms, content, category, is_public, use_count)
VALUES
-- TikTok Templates
('00000000-0000-0000-0000-000000000000', 'TikTok: AI Productivity Hack', 'Create a viral TikTok about an AI productivity hack that saves hours daily', ARRAY['tiktok'], '{"tiktok":{"hook":"I replaced 4 hours of work with 1 AI prompt. Here''s how 👇","caption":"Stop doing everything manually. This AI trick automates your content, emails, and research in seconds.\n\n🧠 Step 1: Pick one repetitive task\n⚡ Step 2: Use an AI bot to handle it\n📈 Step 3: Scale it across platforms\n\nThe future isn''t coming — it''s already here.","visual_prompt":"Fast-paced screen recording showing an AI tool generating content in real-time, split-screen before/after of manual vs automated work, trendy zoom cuts with text overlays","cta":"Follow for more AI hacks that actually work 🤖","hashtags":"#AIHacks #Productivity #WorkSmarter #TechTok #Automation"}}'::jsonb, 'tech', true, 12),

('00000000-0000-0000-0000-000000000000', 'TikTok: Day in My Life as AI Creator', 'Show a day in the life of someone using AI to create content across platforms', ARRAY['tiktok'], '{"tiktok":{"hook":"POV: You make content for 6 platforms in 10 minutes ⏱️","caption":"My morning routine as an AI content creator:\n\n☕ 7am: Coffee + one prompt\n🎬 7:10am: Content for TikTok, IG, LinkedIn, Twitter, FB, Pinterest — done\n🏖️ 7:15am: Rest of the day is mine\n\nThis is what happens when you let AI do the heavy lifting.","visual_prompt":"Aesthetic morning routine montage — person at desk with laptop, satisfying UI clicks generating content, calendar filling up with scheduled posts, ending with person relaxing","cta":"Link in bio to try it yourself ✨","hashtags":"#ContentCreator #DITL #AITools #CreatorEconomy #Lifestyle"}}'::jsonb, 'lifestyle', true, 8),

-- Instagram Templates
('00000000-0000-0000-0000-000000000000', 'Instagram: Build Your AI Brand', 'Create an Instagram carousel about building a personal brand with AI tools', ARRAY['instagram'], '{"instagram":{"hook":"Your brand doesn''t need a team. It needs AI. 🚀","caption":"I went from 0 to consistent content on 6 platforms — without hiring anyone.\n\nHere''s the framework:\n\n1️⃣ Define your niche voice\n2️⃣ Create one AI bot that writes like you\n3️⃣ Generate platform-specific content from a single idea\n4️⃣ Schedule everything in one session\n5️⃣ Track what performs and double down\n\nThe creators winning in 2026 aren''t working harder.\nThey''re building smarter systems.\n\n💬 Save this for later.","visual_prompt":"Clean carousel slides with bold typography on dark gradient backgrounds, each slide covering one step, minimalist icons, brand color accents in purple and blue","cta":"Save 🔖 + Follow for more AI strategies","hashtags":"#PersonalBranding #AIMarketing #ContentStrategy #CreatorTools #DigitalMarketing"}}'::jsonb, 'marketing', true, 15),

('00000000-0000-0000-0000-000000000000', 'Instagram: Behind the Scenes', 'Create a behind-the-scenes Instagram Reel showing AI content creation', ARRAY['instagram'], '{"instagram":{"hook":"What it actually looks like to create a week of content in 15 minutes 👀","caption":"People ask me how I stay so consistent.\n\nThe truth? I batch everything with AI.\n\nOne prompt → six platforms → done.\nThen I spend the rest of my time actually living.\n\nNo burnout. No content anxiety.\nJust a system that works.\n\n🎯 Drop a ''🤖'' if you want me to share my exact workflow.","visual_prompt":"Phone screen recording of the content generation process, aesthetic desk setup with warm lighting, quick cuts showing content appearing for each platform","cta":"Comment ''🤖'' for my free workflow guide","hashtags":"#BTS #ContentCreation #AIContent #ReelsViral #CreatorLife"}}'::jsonb, 'entertainment', true, 6),

-- Facebook Templates
('00000000-0000-0000-0000-000000000000', 'Facebook: AI Success Story', 'Write a Facebook post sharing a relatable AI success story that drives engagement', ARRAY['facebook'], '{"facebook":{"hook":"6 months ago, I was spending 4 hours a day on social media content. Today, I spend 15 minutes.","caption":"Here''s what changed:\n\nI stopped trying to be everywhere manually and started using AI to work smarter.\n\nNow I write one prompt, and my AI generates optimized posts for TikTok, Instagram, LinkedIn, Twitter, Facebook, and Pinterest.\n\nThe result?\n✅ More consistent posting\n✅ Better engagement\n✅ 3 extra hours every single day\n✅ Zero burnout\n\nWho else needs to hear this? Tag them below 👇","visual_prompt":"Split image: left side shows stressed person, right side shows relaxed person with AI dashboard","cta":"Tag a friend who needs this 👇","hashtags":""}}'::jsonb, 'business', true, 10),

('00000000-0000-0000-0000-000000000000', 'Facebook: AI Debate Engagement Post', 'Create a thought-provoking Facebook engagement post about AI in content creation', ARRAY['facebook'], '{"facebook":{"hook":"Honest question: Do you think AI-generated content can be authentic?","caption":"Some people say AI content is ''fake'' or ''lazy.''\nOthers say it''s the smartest way to scale.\n\nHere''s my take: AI doesn''t replace your voice — it amplifies it.\n\nYou still bring the ideas, the perspective, the personality. AI just helps you share it faster.\n\n🅰️ AI content can absolutely be authentic\n🅱️ Nothing beats 100% human-written content\n🅲️ It depends on how you use it\n\nDrop your answer below 👇","visual_prompt":"Bold text overlay on gradient background with A/B/C options visible","cta":"Vote in the comments! 🗳️","hashtags":""}}'::jsonb, 'general', true, 7),

-- Pinterest Templates
('00000000-0000-0000-0000-000000000000', 'Pinterest: AI Tools Infographic', 'Create a Pinterest pin about the best AI tools for content creators in 2026', ARRAY['pinterest'], '{"pinterest":{"hook":"Top 5 AI Tools Every Content Creator Needs in 2026","caption":"Stop wasting time creating content manually. These AI tools will transform your workflow:\n\n1. AI Bot Builders\n2. Multi-Platform Generators\n3. AI Voice Studios\n4. Smart Analytics\n5. Template Libraries\n\n📌 Save this pin for your next content planning session!","visual_prompt":"Tall Pinterest-optimized infographic with numbered list, modern icons, dark theme with purple/blue gradient accents","cta":"Save for later 📌","hashtags":""}}'::jsonb, 'tech', true, 9),

('00000000-0000-0000-0000-000000000000', 'Pinterest: Content Calendar Template', 'Design a Pinterest pin promoting a free AI-powered content calendar strategy', ARRAY['pinterest'], '{"pinterest":{"hook":"Your Free AI Content Calendar for 2026 📅","caption":"Plan a full month of content in 30 minutes using AI:\n\nWeek 1: Educational content\nWeek 2: Behind-the-scenes + personal stories\nWeek 3: Engagement posts\nWeek 4: Promotional + CTA-driven content\n\n🔁 Repeat monthly. Let AI generate the actual posts.\n\n📌 Pin this to your Content Strategy board!","visual_prompt":"Clean calendar-style layout pin with 4 weeks color-coded, minimal design, pastel accent colors on dark background","cta":"Pin to your Strategy board 📌","hashtags":""}}'::jsonb, 'marketing', true, 11),

-- LinkedIn Templates
('00000000-0000-0000-0000-000000000000', 'LinkedIn: The Creator''s Dilemma', 'Write a LinkedIn thought leadership post about the creator economy and AI', ARRAY['linkedin'], '{"linkedin":{"hook":"The biggest lie in the creator economy: ''Just post more.''","caption":"Here''s the truth nobody talks about:\n\nPosting more doesn''t work if every post is mediocre.\n\nWhat works is posting smarter:\n→ One strong idea, adapted for each platform\n→ Platform-native formatting\n→ Consistent voice across every channel\n→ Data-driven iteration\n\nI used to spend 20+ hours per week on content.\nNow I spend 3.\n\nThe difference? I built a system using AI.\n\nThe best creators in 2026 won''t be the ones who grind the hardest.\nThey''ll be the ones who build the best systems.\n\nAgree? ♻️ Repost if this resonates.","visual_prompt":"Professional clean text post design, minimalist quote card with subtle gradient background","cta":"♻️ Repost to help another creator","hashtags":"#ContentCreation #AI #CreatorEconomy #Productivity #PersonalBranding"}}'::jsonb, 'business', true, 14),

('00000000-0000-0000-0000-000000000000', 'LinkedIn: AI ROI Breakdown', 'Create a LinkedIn post with concrete ROI numbers from using AI for content', ARRAY['linkedin'], '{"linkedin":{"hook":"I tracked my content ROI for 90 days after switching to AI tools. Here are the numbers:","caption":"Before AI:\n• 4 hours/day on content creation\n• 3 platforms covered\n• Inconsistent posting\n• Engagement: flat\n\nAfter AI:\n• 30 minutes/day\n• 6 platforms covered\n• Daily posting on all channels\n• Engagement: up 340%\n\nTime saved: ~24 hours/week\nPlatforms: 2x\nConsistency: 100%\n\nAI isn''t a luxury for creators anymore.\nIt''s a competitive advantage.","visual_prompt":"Clean before/after comparison graphic, professional style, data visualization with metrics cards","cta":"Share your experience below 👇","hashtags":"#ROI #AITools #ContentMarketing #DataDriven #CreatorEconomy"}}'::jsonb, 'business', true, 13),

-- Twitter/X Templates
('00000000-0000-0000-0000-000000000000', 'Twitter/X: Viral AI Thread', 'Write a viral Twitter/X thread about how AI is changing content creation', ARRAY['twitter'], '{"twitter":{"hook":"I create content for 6 platforms in under 10 minutes. No team. No scheduling tool. Just AI.\n\nHere''s the exact system (thread) 🧵👇","caption":"1/ The old way: Write a post → manually reformat → spend 4 hours → burnout\n\nThe new way: One prompt → AI generates platform-native content → 10 minutes → done\n\n2/ Each platform has different rules. AI handles the translation. You handle the ideas.\n\n3/ Results after 90 days:\n• 6x more content\n• 340% engagement increase\n• 24 hours/week saved\n• Zero burnout\n\nThe creators who win in 2026 won''t work harder. They''ll build better systems.","visual_prompt":"No image needed for Twitter thread","cta":"RT + Follow for more AI creator tips 🤝","hashtags":""}}'::jsonb, 'tech', true, 10),

('00000000-0000-0000-0000-000000000000', 'Twitter/X: Hot Take on AI Content', 'Write a punchy, curiosity-driven tweet about AI and authenticity', ARRAY['twitter'], '{"twitter":{"hook":"Unpopular opinion: AI-generated content is more authentic than most ''handcrafted'' content.","caption":"Why? Because people using AI actually have time to think about WHAT to say instead of spending all day figuring out HOW to format it.\n\nThe best ideas deserve the best distribution.\nAI is just the vehicle. 🚗\n\nStop gatekeeping tools that make creators'' lives easier.","visual_prompt":"Bold single quote graphic with hot take text, dark background, neon accent color","cta":"Agree or disagree? QRT with your take 🔥","hashtags":""}}'::jsonb, 'motivation', true, 5)

ON CONFLICT DO NOTHING;